# Generated by Django 4.2.13 on 2024-06-09 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'ПСР-проект', 'verbose_name_plural': 'ПСР-проекты'},
        ),
        migrations.RenameField(
            model_name='project',
            old_name='process_boundary',
            new_name='process_boundaries',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_team',
            new_name='team_members',
        ),
        migrations.RemoveField(
            model_name='project',
            name='closure_event',
        ),
        migrations.RemoveField(
            model_name='project',
            name='diagnostics_event',
        ),
        migrations.RemoveField(
            model_name='project',
            name='economic_effect',
        ),
        migrations.RemoveField(
            model_name='project',
            name='improvements_event',
        ),
        migrations.RemoveField(
            model_name='project',
            name='overall_status',
        ),
        migrations.RemoveField(
            model_name='project',
            name='post_monitoring_event',
        ),
        migrations.RemoveField(
            model_name='project',
            name='registration_number',
        ),
        migrations.RemoveField(
            model_name='project',
            name='start_event',
        ),
        migrations.AddField(
            model_name='project',
            name='current_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Текущий показатель'),
        ),
        migrations.AddField(
            model_name='project',
            name='economic_effect_available',
            field=models.BooleanField(default=False, verbose_name='Наличие экономического эффекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='measurement_unit',
            field=models.CharField(max_length=50, null=True, verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='project',
            name='overall_status_comment',
            field=models.TextField(null=True, verbose_name='Общий статус проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='reg_number',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Регистрационный номер'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='target_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Целевой показатель'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_economic_effect',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Фактическая величина экономического эффекта, руб.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_percentage',
            field=models.IntegerField(default=0, verbose_name='Процент завершения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='key_risk',
            field=models.TextField(null=True, verbose_name='Ключевой риск'),
        ),
        migrations.AlterField(
            model_name='project',
            name='optimized_process',
            field=models.CharField(max_length=255, verbose_name='Оптимизируемый процесс'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_economic_effect',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Плановая величина экономического эффекта, руб.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_scope',
            field=models.TextField(null=True, verbose_name='Периметр проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата начала проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершен'), ('in_progress', 'Реализация')], default='draft', max_length=20, verbose_name='Статус проекта'),
        ),
    ]
