# Generated by Django 4.2.13 on 2024-06-03 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0003_department_userprofile_remove_role_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='owner',
        ),
        migrations.AddField(
            model_name='project',
            name='actual_economic_effect',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='additional_risks',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='completion_percentage',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='current_indicator',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='customer_position',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='customer_position', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='diagnosis_target_state',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='goal_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='has_economic_effect',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='improvement_implementation',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='key_risk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='planned_economic_effect',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='post_project_monitoring',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='process',
            field=models.CharField(choices=[('MTO', 'МТО'), ('ETP', 'ЭТП'), ('SP', 'СП'), ('Safety', 'Безопасность'), ('Quality', 'Качество'), ('FEB', 'ФЭБ'), ('Repair/Capital_Construction', 'Ремонт/Кап. Строительство'), ('Office', 'Офисный')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='process_boundaries',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='process_customers',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='process_owner',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_administrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='project_administrator', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='project_manager',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_scope',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_status_comment',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(related_name='project_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='project',
            name='psr_expert',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='results_consolidation_project_closure',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='target_indicator',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='unit_of_measurement',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Завершен'), ('in_progress', 'Реализация')], default='draft', max_length=20),
        ),
    ]
