# Generated by Django 4.2.13 on 2024-06-30 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_optimized_process'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='process_boundaries',
        ),
        migrations.AddField(
            model_name='project',
            name='process_boundary_from',
            field=models.TextField(null=True, verbose_name='Границы процесса от'),
        ),
        migrations.AddField(
            model_name='project',
            name='process_boundary_to',
            field=models.TextField(null=True, verbose_name='Границы процесса до'),
        ),
    ]
