# Generated by Django 4.2.13 on 2024-06-30 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_project_process_boundaries_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='closing_meeting',
            field=models.DateField(null=True, verbose_name='Завершающее совещание и закрытие проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='current_state_building',
            field=models.DateField(null=True, verbose_name='Построение текущего состояния процесса'),
        ),
        migrations.AddField(
            model_name='project',
            name='detailed_plan_development',
            field=models.DateField(null=True, verbose_name='Разработка детального плана мероприятий'),
        ),
        migrations.AddField(
            model_name='project',
            name='improvements_implementation',
            field=models.DateField(null=True, verbose_name='Внедрение улучшений'),
        ),
        migrations.AddField(
            model_name='project',
            name='production_analysis_1',
            field=models.DateField(null=True, verbose_name='Производственный анализ №1'),
        ),
        migrations.AddField(
            model_name='project',
            name='production_analysis_2',
            field=models.DateField(null=True, verbose_name='Производственный анализ №2'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_start',
            field=models.DateField(null=True, verbose_name='Старт проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='survey_1',
            field=models.DateField(blank=True, null=True, verbose_name='Анкетирование №1'),
        ),
        migrations.AddField(
            model_name='project',
            name='survey_2',
            field=models.DateField(blank=True, null=True, verbose_name='Анкетирование №2'),
        ),
        migrations.AddField(
            model_name='project',
            name='target_state_development',
            field=models.DateField(null=True, verbose_name='Разработка целевого состояния процесса'),
        ),
    ]
