# Generated by Django 4.2.13 on 2024-06-03 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_project_description_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='completion_percentage',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='has_economic_effect',
            field=models.BooleanField(choices=[(True, 'Да'), (False, 'Нет')], default=False),
            preserve_default=False,
        ),
    ]
