# Generated by Django 4.2.13 on 2024-06-08 07:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0005_alter_project_completion_percentage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='current_indicator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='diagnosis_target_state',
        ),
        migrations.RemoveField(
            model_name='project',
            name='has_economic_effect',
        ),
        migrations.RemoveField(
            model_name='project',
            name='improvement_implementation',
        ),
        migrations.RemoveField(
            model_name='project',
            name='post_project_monitoring',
        ),
        migrations.RemoveField(
            model_name='project',
            name='process',
        ),
        migrations.RemoveField(
            model_name='project',
            name='process_boundaries',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_administrator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_start',
        ),
        migrations.RemoveField(
            model_name='project',
            name='project_status_comment',
        ),
        migrations.RemoveField(
            model_name='project',
            name='results_consolidation_project_closure',
        ),
        migrations.RemoveField(
            model_name='project',
            name='target_indicator',
        ),
        migrations.RemoveField(
            model_name='project',
            name='unit_of_measurement',
        ),
        migrations.AddField(
            model_name='project',
            name='closure_event',
            field=models.DateField(blank=True, null=True, verbose_name='Закрепление результатов и закрытие проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='diagnostics_event',
            field=models.DateField(blank=True, null=True, verbose_name='Диагностика и Целевое состояние'),
        ),
        migrations.AddField(
            model_name='project',
            name='economic_effect',
            field=models.CharField(choices=[('yes', 'да'), ('no', 'нет')], default='no', max_length=3, verbose_name='Наличие экономического эффекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='improvements_event',
            field=models.DateField(blank=True, null=True, verbose_name='Внедрение улучшений'),
        ),
        migrations.AddField(
            model_name='project',
            name='optimized_process',
            field=models.CharField(choices=[('MTO', 'МТО'), ('ETP', 'ЭТП'), ('SP', 'СП'), ('Safety', 'Безопасность'), ('Quality', 'Качество'), ('FEB', 'ФЭБ'), ('Repair', 'Ремонт/Кап. Строительство'), ('Office', 'Офисный')], default=' ', max_length=255, verbose_name='Оптимизируемый процесс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='project',
            name='overall_status',
            field=models.TextField(default='', verbose_name='Общий статус проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='post_monitoring_event',
            field=models.DateField(blank=True, null=True, verbose_name='Постпроектный мониторинг'),
        ),
        migrations.AddField(
            model_name='project',
            name='process_boundary',
            field=models.TextField(null=True, verbose_name='Границы процесса'),
        ),
        migrations.AddField(
            model_name='project',
            name='project_admin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_projects', to=settings.AUTH_USER_MODEL, verbose_name='Администратор проекта'),
        ),
        migrations.AddField(
            model_name='project',
            name='start_event',
            field=models.DateField(blank=True, null=True, verbose_name='Старт проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='actual_economic_effect',
            field=models.DecimalField(decimal_places=2, default=' ', max_digits=10, verbose_name='Фактическая величина экономического эффекта, руб.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='additional_risks',
            field=models.TextField(null=True, verbose_name='Дополнительные риски'),
        ),
        migrations.AlterField(
            model_name='project',
            name='completion_percentage',
            field=models.FloatField(default=0, verbose_name='Процент завершения'),
        ),
        migrations.AlterField(
            model_name='project',
            name='customer',
            field=models.CharField(default=' ', max_length=255, verbose_name='Заказчик проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='customer_position',
            field=models.CharField(default='', max_length=255, verbose_name='Должность заказчика'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='goal_name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование цели'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='key_risk',
            field=models.TextField(default='', verbose_name='Ключевой риск'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='Наименование ПСР-проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_economic_effect',
            field=models.DecimalField(decimal_places=2, default='', max_digits=10, verbose_name='Плановая величина экономического эффекта, руб.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='process_customers',
            field=models.CharField(default='', max_length=255, verbose_name='Заказчики процесса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='process_owner',
            field=models.CharField(default='', max_length=255, verbose_name='Владелец процесса'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_manager',
            field=models.CharField(default='', max_length=255, verbose_name='Руководитель проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_scope',
            field=models.TextField(default='', verbose_name='Периметр проекта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='project_team',
            field=models.ManyToManyField(related_name='team_projects', to=settings.AUTH_USER_MODEL, verbose_name='Команда проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='psr_expert',
            field=models.CharField(default='', max_length=255, verbose_name='Эксперт от ПСР'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='registration_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Регистрационный номер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Дата начала проекта'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('in_progress', 'Реализация'), ('completed', 'Завершен')], default='draft', max_length=20, verbose_name='Статус проекта'),
        ),
    ]
