# Generated by Django 4.2.13 on 2024-07-02 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_project_closing_meeting_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='process_owner_position',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность владельца'),
        ),
    ]
