# Generated by Django 4.2.13 on 2024-07-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_project_process_owner_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_manager_position',
            field=models.CharField(max_length=255, null=True, verbose_name='Должность руководителя проекта'),
        ),
    ]
