# Generated by Django 4.2.13 on 2024-06-08 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_task_description_alter_task_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='actual_economic_effect',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Фактическая величина экономического эффекта, руб.'),
        ),
        migrations.AlterField(
            model_name='project',
            name='planned_economic_effect',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Плановая величина экономического эффекта, руб.'),
        ),
    ]
