# Generated by Django 4.2.13 on 2024-08-27 19:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0009_project_project_manager_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('document_type', models.CharField(choices=[('checklist', 'Проверочный лист ПСР-проекта'), ('survey', 'Анкетирование заказчиков процесса'), ('template', 'Шаблон карточки ПСР-проекта'), ('report', 'Отчёт о ходе реализации ПСР-проекта'), ('change_request', 'Запрос на изменение ПСР-проекта'), ('completion_report', 'Отчёт о завершении ПСР-проекта'), ('order', 'Приказ о старте реализации ПСР-проекта'), ('plan', 'Детальный план мероприятий по ПСР-проекту'), ('analysis', 'Производственный анализ')], max_length=50)),
                ('file', models.FileField(upload_to='project_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='team_members',
            field=models.ManyToManyField(null=True, related_name='team_projects', to=settings.AUTH_USER_MODEL, verbose_name='Команда проекта'),
        ),
    ]
